/**
 * song_data.h
 * Externs for the song embedded in the Vitis ELF.
 *
 * The actual song_data.c is generated by tools/gen_song_data.py.
 * The default committed song_data.c contains 32768 zero samples (silence),
 * which lets the build succeed without a real song. Run the generator with
 * a WAV file to overwrite it with real audio.
 */

#ifndef SONG_DATA_H
#define SONG_DATA_H

#include "xil_types.h"

/* The full song as 16-bit signed PCM at 11025 Hz, mono. */
extern const int16_t  song_data[];

/* Total number of valid samples in song_data[]. */
extern const uint32_t song_total_samples;

/* Chunk size in samples (matches BRAM depth). PS streams one chunk per wrap. */
extern const uint32_t song_chunk_samples;

/* Sample rate the song was generated at (informational). */
extern const uint32_t song_sample_rate;

#endif /* SONG_DATA_H */
