#!/usr/bin/env python3
"""
gen_audio_coe.py — Convert a WAV file to a Xilinx BRAM .coe initialization file.

Usage:
    python gen_audio_coe.py input.wav output.coe [num_samples] [sample_rate]

Defaults:
    num_samples = 65536   (matches audio_sample_reader SAMPLE_COUNT default)
    sample_rate = 22050   (matches audio_sample_reader SAMPLE_RATE default)

The script:
  - Reads any WAV file (mono or stereo, 8 or 16-bit, any rate)
  - Mixes to mono (first channel if stereo)
  - Resamples to target rate using linear interpolation
  - Pads with silence or truncates to num_samples
  - Writes a hex COE file suitable for Xilinx blk_mem_gen initialization
"""

import sys
import os
import wave
import struct
import math


def read_wav(path):
    with wave.open(path, 'r') as w:
        channels  = w.getnchannels()
        sampwidth = w.getsampwidth()
        framerate = w.getframerate()
        nframes   = w.getnframes()
        raw       = w.readframes(nframes)

    if sampwidth == 1:
        fmt = f'{nframes * channels}B'
        raw_int = [(b - 128) * 256 for b in struct.unpack(fmt, raw)]
    elif sampwidth == 2:
        fmt = f'<{nframes * channels}h'
        raw_int = list(struct.unpack(fmt, raw))
    elif sampwidth == 3:
        raw_int = []
        for i in range(0, len(raw), 3 * channels):
            for c in range(channels):
                off = i + c * 3
                val = struct.unpack('<i', raw[off:off+3] + b'\x00')[0] >> 8
                raw_int.append(val)
    elif sampwidth == 4:
        fmt = f'<{nframes * channels}i'
        raw_int = [v >> 16 for v in struct.unpack(fmt, raw)]
    else:
        raise ValueError(f"Unsupported sample width: {sampwidth} bytes")

    # Mix to mono (take first channel)
    if channels > 1:
        mono = raw_int[::channels]
    else:
        mono = raw_int

    return mono, framerate


def resample(samples, src_rate, dst_rate):
    if src_rate == dst_rate:
        return samples
    ratio     = src_rate / dst_rate
    out_len   = int(len(samples) / ratio)
    out       = []
    for i in range(out_len):
        pos  = i * ratio
        lo   = int(pos)
        frac = pos - lo
        hi   = min(lo + 1, len(samples) - 1)
        val  = int(samples[lo] * (1.0 - frac) + samples[hi] * frac)
        out.append(val)
    return out


def write_coe(samples, path, num_samples, sample_rate):
    # Pad or truncate
    if len(samples) >= num_samples:
        out = samples[:num_samples]
    else:
        out = samples + [0] * (num_samples - len(samples))

    with open(path, 'w') as f:
        f.write(f'; 16-bit signed PCM audio\n')
        f.write(f'; {num_samples} samples @ {sample_rate} Hz\n')
        f.write(f'; Generated by gen_audio_coe.py\n')
        f.write('memory_initialization_radix=16;\n')
        f.write('memory_initialization_vector=\n')
        for i, s in enumerate(out):
            val = s & 0xFFFF
            sep = ',' if i < num_samples - 1 else ';'
            f.write(f'{val:04X}{sep}\n')


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    wav_path    = sys.argv[1]
    coe_path    = sys.argv[2]
    num_samples = int(sys.argv[3]) if len(sys.argv) > 3 else 65536
    sample_rate = int(sys.argv[4]) if len(sys.argv) > 4 else 22050

    if not os.path.exists(wav_path):
        print(f"ERROR: {wav_path} not found")
        sys.exit(1)

    print(f"Reading  : {wav_path}")
    samples, src_rate = read_wav(wav_path)
    print(f"Source   : {len(samples)} samples @ {src_rate} Hz (mono)")

    if src_rate != sample_rate:
        print(f"Resample : {src_rate} Hz → {sample_rate} Hz")
        samples = resample(samples, src_rate, sample_rate)
        print(f"Resampled: {len(samples)} samples")

    duration = len(samples) / sample_rate
    target_s = num_samples / sample_rate
    print(f"Duration : {duration:.2f}s source, {target_s:.2f}s target ({num_samples} samples)")

    if len(samples) < num_samples:
        print(f"Padding  : {num_samples - len(samples)} zero samples")
    elif len(samples) > num_samples:
        print(f"Truncate : keeping first {num_samples} samples")

    write_coe(samples, coe_path, num_samples, sample_rate)
    print(f"Written  : {coe_path}")
    print(f"Load this file in Vivado: blk_mem_gen_0 → Port A Options → Memory Initialization File")


if __name__ == '__main__':
    main()
