#!/usr/bin/env python3
"""
gen_song_data.py — Convert a WAV file into a C source file embeddable in the
Vitis ELF for full-song streaming, and refresh the BRAM init COE with the
first chunk of the same song.

Usage:
    python gen_song_data.py input.wav [sw/src/song_data.c] [data/audio_samples.coe]

Defaults:
    output_c   = sw/src/song_data.c
    output_coe = data/audio_samples.coe
    sample_rate = 11025      (matches reactive_scene_top_ps.v SAMPLE_RATE)
    chunk_size  = 32768      (matches BRAM depth)

Pipeline:
    1. Read WAV (mono or stereo, 8/16/24/32-bit)
    2. Mix to mono, resample to 11025 Hz (linear interpolation)
    3. Write entire song as `const int16_t song_data[N]` to song_data.c
    4. Write first chunk_size samples to a Vivado COE for synth-time BRAM init
       (so audio plays from boot even before the Vitis app streams more)

Convert MP3 to WAV first (Audacity / ffmpeg / online):
    ffmpeg -i mysong.mp3 -ac 1 -ar 11025 mysong.wav
"""

import sys
import os
import wave
import struct


def read_wav(path):
    with wave.open(path, 'r') as w:
        channels  = w.getnchannels()
        sampwidth = w.getsampwidth()
        framerate = w.getframerate()
        nframes   = w.getnframes()
        raw       = w.readframes(nframes)

    if sampwidth == 1:
        fmt = f'{nframes * channels}B'
        raw_int = [(b - 128) * 256 for b in struct.unpack(fmt, raw)]
    elif sampwidth == 2:
        fmt = f'<{nframes * channels}h'
        raw_int = list(struct.unpack(fmt, raw))
    elif sampwidth == 3:
        raw_int = []
        for i in range(0, len(raw), 3 * channels):
            for c in range(channels):
                off = i + c * 3
                val = struct.unpack('<i', raw[off:off+3] + b'\x00')[0] >> 8
                raw_int.append(val)
    elif sampwidth == 4:
        fmt = f'<{nframes * channels}i'
        raw_int = [v >> 16 for v in struct.unpack(fmt, raw)]
    else:
        raise ValueError(f"Unsupported sample width: {sampwidth} bytes")

    if channels > 1:
        mono = raw_int[::channels]
    else:
        mono = raw_int

    return mono, framerate


def resample(samples, src_rate, dst_rate):
    if src_rate == dst_rate:
        return samples
    ratio   = src_rate / dst_rate
    out_len = int(len(samples) / ratio)
    out     = []
    for i in range(out_len):
        pos  = i * ratio
        lo   = int(pos)
        frac = pos - lo
        hi   = min(lo + 1, len(samples) - 1)
        val  = int(samples[lo] * (1.0 - frac) + samples[hi] * frac)
        out.append(val)
    return out


def write_song_c(samples, path, sample_rate, chunk_size):
    """Write the full song as a C array."""
    n = len(samples)
    duration = n / sample_rate
    chunks   = (n + chunk_size - 1) // chunk_size

    with open(path, 'w') as f:
        f.write('/*\n')
        f.write(' * song_data.c -- AUTO-GENERATED by tools/gen_song_data.py\n')
        f.write(' *\n')
        f.write(f' * {n} samples @ {sample_rate} Hz = {duration:.2f} seconds\n')
        f.write(f' * {chunks} chunks of {chunk_size} samples each (~{chunk_size/sample_rate:.2f}s per chunk)\n')
        f.write(' *\n')
        f.write(' * Embedded in the Vitis ELF; PS streams chunks into BRAM via AXI BRAM ctrl.\n')
        f.write(' * Do not edit by hand. Re-run gen_song_data.py to regenerate.\n')
        f.write(' */\n\n')
        f.write('#include "song_data.h"\n\n')
        f.write(f'const uint32_t song_total_samples = {n};\n')
        f.write(f'const uint32_t song_chunk_samples = {chunk_size};\n')
        f.write(f'const uint32_t song_sample_rate  = {sample_rate};\n\n')
        f.write('const int16_t song_data[] = {\n')

        # Write 8 samples per line, 6-char hex format like 0xFF12
        for i in range(0, n, 8):
            line = '    '
            chunk_vals = samples[i:i+8]
            for v in chunk_vals:
                v16 = v & 0xFFFF
                line += f'(int16_t)0x{v16:04X}, '
            f.write(line + '\n')

        f.write('};\n')


def write_coe(samples, path, chunk_size, sample_rate):
    """Write the FIRST chunk_size samples as a Vivado COE for BRAM init."""
    if len(samples) >= chunk_size:
        first = samples[:chunk_size]
    else:
        first = samples + [0] * (chunk_size - len(samples))

    with open(path, 'w') as f:
        f.write('; 16-bit signed PCM audio, zero-extended to 32 bits\n')
        f.write(f'; First {chunk_size} samples of song @ {sample_rate} Hz\n')
        f.write('; Generated by gen_song_data.py (BRAM init for synth time)\n')
        f.write('memory_initialization_radix=16;\n')
        f.write('memory_initialization_vector=\n')
        for i, s in enumerate(first):
            val = s & 0xFFFF
            sep = ',' if i < chunk_size - 1 else ';'
            f.write(f'0000{val:04X}{sep}\n')


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    wav_path    = sys.argv[1]
    c_path      = sys.argv[2] if len(sys.argv) > 2 else 'sw/src/song_data.c'
    coe_path    = sys.argv[3] if len(sys.argv) > 3 else 'data/audio_samples.coe'
    sample_rate = 11025
    chunk_size  = 32768

    if not os.path.exists(wav_path):
        print(f"ERROR: {wav_path} not found")
        sys.exit(1)

    if wav_path.lower().endswith('.mp3'):
        print(f"ERROR: {wav_path} is an MP3 file. This script only reads WAV.")
        print()
        print("Convert it first using one of:")
        print("  - Audacity:  File -> Open -> Export -> WAV signed 16-bit PCM")
        print("  - VLC:       Media -> Convert/Save -> Profile 'Audio - WAV'")
        print("  - ffmpeg:    ffmpeg -i input.mp3 -ac 1 -ar 11025 output.wav")
        print("  - Online:    https://cloudconvert.com/mp3-to-wav")
        print()
        print("Then re-run with the .wav path:")
        print(f"  python tools/gen_song_data.py {wav_path[:-4]}.wav")
        sys.exit(1)

    print(f"Reading  : {wav_path}")
    samples, src_rate = read_wav(wav_path)
    print(f"Source   : {len(samples)} samples @ {src_rate} Hz (mono)")

    if src_rate != sample_rate:
        print(f"Resample : {src_rate} Hz -> {sample_rate} Hz")
        samples = resample(samples, src_rate, sample_rate)
        print(f"Resampled: {len(samples)} samples")

    duration = len(samples) / sample_rate
    chunks   = (len(samples) + chunk_size - 1) // chunk_size
    print(f"Duration : {duration:.2f}s ({chunks} chunk{'' if chunks == 1 else 's'} of {chunk_size} samples)")

    write_song_c(samples, c_path, sample_rate, chunk_size)
    print(f"Written  : {c_path}")

    write_coe(samples, coe_path, chunk_size, sample_rate)
    print(f"Written  : {coe_path}  (first {chunk_size} samples for BRAM init)")

    print()
    print("Next steps:")
    print("  1. Re-synthesize Vivado (BRAM picks up new COE at synth time):")
    print("       reset_run design_1_axi_bram_ctrl_0_bram_0_1_synth_1")
    print("       reset_run synth_1; launch_runs synth_1 -jobs 4; wait_on_run synth_1")
    print("       reset_run impl_1; launch_runs impl_1 -to_step write_bitstream -jobs 4; wait_on_run impl_1")
    print("  2. Re-export hardware:  write_hw_platform -fixed -include_bit -force ...")
    print("  3. Rebuild Vitis app (it will pick up new song_data.c automatically)")
    print("  4. Program FPGA, then Launch Hardware in Vitis to start streaming")


if __name__ == '__main__':
    main()
